### ISSUE TITLE
TypeError: StreamingDataset.__init__() got an unexpected keyword argument 'right_padding'

### ISSUE THREAD

**Issue by germanjke** [databricks/compose-rl#26]
Hi, i'm created data from your example 

My data loaders looks like:

```
train_loader:
  name: pairwise_preference
  dataset:
    local: /data/pred_data
    remote: s3://path
    split: train_prefs 
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${seed}
  drop_last: true
  num_workers: 8

eval_loader:
  name: pairwise_preference
  dataset:
    local: /data/pred_data
    remote: s3://path
    split: test_prefs 

    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${seed}
  drop_last: true
  num_workers: 8
```

But getting `TypeError: StreamingDataset.__init__() got an unexpected keyword argument 'right_padding'`

I install everything before train

```
git clone https://github.com/databricks/compose-rl.git
cd compose-rl
pip install -e .[gpu]
```

Full traceback

```
task-0: INFO:__main__:Building tokenizer...
task-0: INFO:__main__:Building train loader...
task-0: [rank7]: Traceback (most recent call last):
task-0: [rank7]:   File "/tgpt/llm-foundry/scripts/train/train.py", line 717, in <module>
task-0: [rank7]:     main(cfg)
task-0: [rank7]:   File "/tgpt/llm-foundry/scripts/train/train.py", line 421, in main
task-0: [rank7]:     train_loader = build_dataloader(
task-0: [rank7]:                    ^^^^^^^^^^^^^^^^^
task-0: [rank7]:   File "/usr/lib/python3/dist-packages/llmfoundry/data/dataloader.py", line 39, in build_dataloader
task-0: [rank7]:     return construct_from_registry(
task-0: [rank7]:            ^^^^^^^^^^^^^^^^^^^^^^^^
task-0: [rank7]:   File "/usr/lib/python3/dist-packages/llmfoundry/utils/registry_utils.py", line 160, in construct_from_registry
task-0: [rank7]:     constructed_item = registered_constructor(**kwargs)
task-0: [rank7]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
task-0: [rank7]:   File "/tgpt/compose-rl/compose_rl/data/dataloader.py", line 75, in build_preference_dataloader
task-0: [rank7]:     streaming_dataset = dataset_cls(
task-0: [rank7]:                         ^^^^^^^^^^^^
task-0: [rank7]:   File "/tgpt/compose-rl/compose_rl/data/preference_data.py", line 203, in __init__
task-0: [rank7]:     super().__init__(**kwargs)
task-0: [rank7]: TypeError: StreamingDataset.__init__() got an unexpected keyword argument 'right_padding'
```

Do you know what is problem?

Thank you
